const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    VERIFY_SUCCESS: 'VERIFY_SUCCESS',
    VERIFY_FAIL: 'VERIFY_FAIL',
    RESEND_CODE_SUCCESS: 'RESEND_CODE_SUCCESS',
    RESEND_CODE_FAIL: 'RESEND_CODE_FAIL',
    // Add any other action types here if needed
};

export default actionTypes;