export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as VerificationPage } from './VerificationPage'
export { default as ForgetPassword } from './ForgetPassword'
export { default as Home } from './Home'
export { default as CategoryPage } from './CategoryPage'
export { default as Search } from './Search'
export { default as DetailPage } from './DetailPage'
export { default as DetailItem } from './DetailItem'
export { default as List} from './List'
export { default as ServicePage } from './ServicePage'
export { default as FeedbackPage } from './FeedbackPage'
export { default as SlideShow } from './SlideShow'
export { default as NewPost } from './NewPost'
export { default as ManagePostPage } from './ManagePostPage'
export { default as UpdateProfilePage } from './UpdateProfilePage'
export { default as RechargePage } from './RechargePage'
export { default as RechargeHistoryPage } from './RechargeHistoryPage'
export { default as PaymentHistoryPage } from './PaymentHistoryPage'
export { default as SearchPage } from './SearchPage'
export { default as MomoPage } from './MomoPage'
export {default as Payment } from './Payment'